apiVersion: v1
kind: Service
metadata: 
  name: pankaj-service-clusterip
  labels: 
    app: service-label-clusteip
spec: 
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pankaj-pod
  ports: 
    - protocol: TCP
      port: 80 
      targetPort: 80
