apiVersion: v1
kind: Service
metadata:
  name: demo-service  # Can call it anything
  namespace: demo-ns           # Define a specific namespace
  labels:
    app: service-label-nodeport    #
spec:
  type: NodePort
  selector:
    app: demo-pod-app-deployment
    type: demo-front-end-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
