apiVersion: v1
kind: Service
metadata:
  name: default-service-nordport
  labels:
    app: service-label-nodeport
spec:
  type: NodePort
  selector:
    app: pod-app-deployment
    type: front-end-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010
